[workspace]
members = [
    "crates/neatcoder",
    "crates/parser",
    "crates/oai",
    "crates/wasmer"
]
exclude = [
    "examples/projects/*/jobs/codebase",
]

[profile.release]
debug = true

[profile.dev]
debug = true
