[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# [[bin]]
# name = "default"
# path = "src/bin/default.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
