[package]
name = "llm-store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = "2.1"
sha2 = "0.10"
anyhow = "1.0"
sha3 = "0.10"
hex = "0.4.3"